# Copyright: Ankitects Pty Ltd and contributors
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

"""Speedrun (MCAT fork) helpers.

Two responsibilities live here:

1. Thin wrappers over the Rust ``SpeedrunService`` RPCs, plus the minimal
   miss-reason flow: classify a missed question, persist the latest reason as a
   ``miss::<reason>`` note tag (D-11; never ``card.custom_data``), and call
   gated activation.
2. Desktop data-model provisioning (D-13): idempotently create the
   ``SpeedrunQuestion`` notetype, the ``Speedrun::Questions`` deck, and a
   starter MCAT ``speedrunBlueprint`` config. The engine's activation/mastery
   logic is *not* re-implemented here — we only create native objects and call
   the frozen RPCs.
3. Real question-bank import (D-4): a one-time, idempotent import of a vendored,
   legally reusable MCAT-relevant question bank (see ``import_question_bank``)
   into native ``SpeedrunQuestion`` notes. Because they are native objects, a
   single desktop import syncs to Android/other devices for free (D-2). The
   imported bank is the *only* source of served practice questions — there is
   no synthetic/demo content, and the study loop is gated on having imported it.
4. First-principles memory cards (D-2a): the questions only *grade*; they gate
   the activation of linked memory flashcards. Those are original, hand-authored
   first-principles cards (see ``import_first_principles``) that teach the
   concept a family of questions tests — never a restatement of a specific bank
   item, and not part of the served/heldout question set. They link to questions
   by a shared ``topic::`` tag and are imported suspended until a related miss
   activates them.
"""

from __future__ import annotations

import gzip
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

import anki
import anki.collection
from anki import speedrun_pb2
from anki.notes import Note, NoteId

if TYPE_CHECKING:
    from anki.decks import DeckId
    from anki.models import NotetypeId

# public exports
MissReason = speedrun_pb2.MissReason
ActivateCardsResponse = speedrun_pb2.ActivateCardsResponse
MemoryScoreResponse = speedrun_pb2.MemoryScoreResponse

# Tag prefix for the latest miss reason on a question note (D-11).
MISS_TAG_PREFIX = "miss::"

# Map each MissReason to the tag suffix used by the SPOV3 taxonomy.
_MISS_REASON_TAG_SUFFIX: dict[int, str] = {
    MissReason.KNOWLEDGE_GAP: "knowledge-gap",
    MissReason.MISSING_CONTEXT: "missing-context",
    MissReason.MISUNDERSTANDING: "misunderstanding",
    MissReason.CARELESS: "careless",
}

# --- Native data model (T1 / D-13) -------------------------------------------

#: The runtime-provisioned question notetype. Provisioned via a helper rather
#: than as a stock notetype to keep the fork mergeable (D-13).
QUESTION_NOTETYPE_NAME = "SpeedrunQuestion"
#: Field order is part of the frozen data-model contract (C1).
QUESTION_FIELDS = (
    "stem",
    "options",
    "correct",
    "explanation",
    "source",
    "difficulty_b",
    "discrimination_a",
)
#: Served practice questions live in their own deck.
QUESTIONS_DECK_NAME = "Speedrun::Questions"
#: Linked flashcards (normal notes, suspended by default) live here.
FLASHCARDS_DECK_NAME = "Speedrun::Cards"

# Tag taxonomy (must match the Rust engine's constants).
TOPIC_TAG_PREFIX = "topic::"
POOL_SERVED_TAG = "pool::served"
POOL_HELDOUT_TAG = "pool::heldout"
#: Legacy marker tag from the old synthetic demo dataset. No new demo content is
#: ever created; this is kept only so :meth:`Speedrun.purge_demo_data` can find
#: and delete any synthetic notes left in a collection provisioned by an older
#: build (D-10 / D-16: synthetic placeholders must never masquerade as content).
LEGACY_DEMO_TAG = "speedrun-demo"

# Real question-bank import (D-4 / D-16) ---------------------------------------
#
# Unlike the synthetic demo above, this imports a *real*, legally reusable bank
# of MCAT-relevant questions (OpenMCAT + MMLU; see the repo README for full
# attribution) as native ``SpeedrunQuestion`` notes. Because questions are
# native Anki objects, a single desktop import syncs to every device for free —
# no per-device re-import, no side tables (D-2). The bank is regenerated by
# ``tools/speedrun/build_question_bank.py`` and vendored as JSON alongside this
# module so import is deterministic and works offline.

#: Marker tag on every imported bank note (find/remove/report the whole bank).
BANK_TAG = "speedrun-bank"
#: Per-note stable id tag, used to make re-import idempotent (never duplicates).
BANK_UID_TAG_PREFIX = "bankuid::"
#: Per-note origin tag, e.g. ``bank::openmcat`` / ``bank::mmlu``.
BANK_SOURCE_TAG_PREFIX = "bank::"
#: Tag marking third-party AI-generated items so the M2 eval harness can find
#: and gate them (D-9); they are honestly labelled rather than hidden.
BANK_AI_GENERATED_TAG = "bank::ai-generated"
#: Vendored, pre-normalized bank shipped next to this module (resolves in dev,
#: tests, and the wheel via the package dir). Gzipped so the repo carries a
#: single small binary blob instead of a huge JSON text diff.
DEFAULT_BANK_PATH = (
    Path(__file__).parent / "data" / "speedrun_question_bank.json.gz"
)


def load_question_bank(path: str | Path | None = None) -> dict[str, Any]:
    """Load and parse the vendored question bank JSON (gzip or plain).

    Kept module-level so tests and tooling can read the bank without a
    collection. ``path`` defaults to the vendored gzipped bank.
    """
    bank_path = Path(path) if path is not None else DEFAULT_BANK_PATH
    if bank_path.suffix == ".gz":
        with gzip.open(bank_path, "rt", encoding="utf-8") as fh:
            return json.load(fh)
    with open(bank_path, encoding="utf-8") as fh:
        return json.load(fh)


# First-principles memory cards (D-2a linked flashcards) -----------------------
#
# The imported questions only *grade* the student; they gate the activation of
# linked *memory flashcards*. Those cards are original, hand-authored MCAT
# first-principles items (vendored next to this module) that teach the concept a
# family of questions tests — they deliberately never restate a specific bank
# question and are not part of the served/heldout question set. They link to
# questions purely by a shared ``topic::`` tag, are imported as *suspended*
# Basic notes into ``Speedrun::Cards``, and are unsuspended only when a related
# question is missed for a memory reason (or by a coverage sweep).

#: Notetype used for the linked memory cards (stock two-field Basic).
FLASHCARD_NOTETYPE_NAME = "Basic"
#: Marker tag on every first-principles card (find/remove/report the whole set).
FIRST_PRINCIPLES_TAG = "speedrun-first-principles"
#: Per-card stable id tag, used to make re-import idempotent (never duplicates).
FIRST_PRINCIPLES_UID_TAG_PREFIX = "fpuid::"
#: Fine-grained concept tag (e.g. ``concept::electrochemistry``) for auditing.
CONCEPT_TAG_PREFIX = "concept::"
#: Vendored, hand-authored first-principles dataset shipped next to this module.
DEFAULT_FIRST_PRINCIPLES_PATH = (
    Path(__file__).parent / "data" / "speedrun_first_principles.json"
)


def load_first_principles(path: str | Path | None = None) -> dict[str, Any]:
    """Load and parse the vendored first-principles card dataset.

    Kept module-level so tests and tooling can read the set without a
    collection. ``path`` defaults to the vendored JSON.
    """
    fp_path = Path(path) if path is not None else DEFAULT_FIRST_PRINCIPLES_PATH
    with open(fp_path, encoding="utf-8") as fh:
        return json.load(fh)

# Config keys (must match rslib/src/speedrun/blueprint.rs + config/bool.rs).
BLUEPRINT_CONFIG_KEY = "speedrunBlueprint"
SWEEP_SAMPLE_SIZE_CONFIG_KEY = "speedrunSweepSampleSize"
ORDERING_CONFIG_KEY = "speedrunOrdering"
#: Persisted paused guided-session progress (written by ``aqt.speedrun.session``).
#: Defined here so both the session controller and :meth:`Speedrun.reset_profile`
#: refer to the same key.
SESSION_STATE_CONFIG_KEY = "speedrunSessionState"

# Guided-session per-phase caps (Tier 2). Tunable via collection config so the
# fixed sequence never floods the student (adaptive/capped sizing). Defaults are
# deliberately small to avoid cognitive overload.
SESSION_PRACTICE_CAP_CONFIG_KEY = "speedrunSessionPracticeCap"
SESSION_FLASHCARD_CAP_CONFIG_KEY = "speedrunSessionFlashcardCap"
SESSION_RECAP_CAP_CONFIG_KEY = "speedrunSessionRecapCap"
DEFAULT_SESSION_PRACTICE_CAP = 10
DEFAULT_SESSION_FLASHCARD_CAP = 20
DEFAULT_SESSION_RECAP_CAP = 5

#: Starter MCAT blueprint: AAMC-style *topic labels and approximate relative
#: weights only*.
#:
#: LICENSING (D-3 / D-16): these are topic labels and approximate weights, NOT
#: copyrighted AAMC text or MCAT items. They are a placeholder for demoing
#: value-ordering / coverage / readiness and must be reviewed for licensing
#: before shipping. Weights are relative magnitudes (they happen to sum to 1.0).
DEFAULT_MCAT_BLUEPRINT: dict[str, Any] = {
    "topics": [
        {"name": "biochemistry", "weight": 0.25},
        {"name": "biology", "weight": 0.18},
        {"name": "general-chemistry", "weight": 0.13},
        {"name": "organic-chemistry", "weight": 0.10},
        {"name": "physics", "weight": 0.09},
        {"name": "psychology", "weight": 0.15},
        {"name": "sociology", "weight": 0.10},
    ]
}


@dataclass
class SessionCaps:
    """Per-phase question/card caps for a guided session (Tier 2)."""

    practice: int
    flashcards: int
    recap: int


@dataclass
class SetupSummary:
    """What ``setup_mcat`` provisioned, for surfacing in the UI."""

    notetype_id: int
    questions_deck_id: int
    flashcards_deck_id: int
    blueprint_topics: int
    #: True once the real question bank has been imported (served questions
    #: exist). Practice is gated on this being true.
    bank_imported: bool = False
    #: Number of served practice questions currently available.
    served_question_count: int = 0
    #: How many leftover synthetic demo notes were purged during setup.
    demo_notes_removed: int = 0


@dataclass
class BankImportSummary:
    """Outcome of importing the vendored question bank."""

    total_in_bank: int = 0
    imported: int = 0
    skipped_existing: int = 0
    by_origin: dict[str, int] = field(default_factory=dict)
    by_pool: dict[str, int] = field(default_factory=dict)
    by_topic: dict[str, int] = field(default_factory=dict)
    attribution: list[dict[str, str]] = field(default_factory=list)


@dataclass
class FirstPrinciplesImportSummary:
    """Outcome of importing the first-principles memory cards."""

    total: int = 0
    imported: int = 0
    skipped_existing: int = 0
    suspended: int = 0
    by_topic: dict[str, int] = field(default_factory=dict)


@dataclass
class ResetProfileSummary:
    """Outcome of resetting the learner's Speedrun progress.

    The imported question bank and memory cards are always kept; only the
    learner's *progress* (activation + FSRS review history + any paused session)
    is cleared.
    """

    #: Memory cards that were active (unsuspended) and got returned to suspended.
    cards_resuspended: int = 0
    #: Memory cards that had scheduling/FSRS history that was cleared.
    cards_forgotten: int = 0
    #: Whether a paused guided-session state was cleared.
    session_cleared: bool = False


def topic_of_note(note: Note) -> str | None:
    """Return the bare topic name from a note's first ``topic::`` tag, if any."""
    for tag in note.tags:
        if tag.startswith(TOPIC_TAG_PREFIX):
            return tag[len(TOPIC_TAG_PREFIX) :]
    return None


def _round_robin(groups: list[list[NoteId]]) -> list[NoteId]:
    """Interleave per-topic note-id lists so consecutive items differ in topic."""
    result: list[NoteId] = []
    cursors = [0] * len(groups)
    remaining = sum(len(g) for g in groups)
    while remaining:
        for i, group in enumerate(groups):
            if cursors[i] < len(group):
                result.append(group[cursors[i]])
                cursors[i] += 1
                remaining -= 1
    return result


def option_lines(options_field: str) -> list[str]:
    """Split a question's ``options`` field into trimmed, non-empty lines."""
    return [line.strip() for line in options_field.splitlines() if line.strip()]


def correct_index(correct_field: str, num_options: int) -> int:
    """Resolve a ``correct`` field to a 0-based option index, or -1 if invalid.

    Accepts a letter (``A``-``D``, case-insensitive) or a 1-based number.
    """
    text = correct_field.strip()
    if not text:
        return -1
    if text[0].isalpha():
        idx = ord(text[0].upper()) - ord("A")
    else:
        try:
            idx = int(text) - 1
        except ValueError:
            return -1
    return idx if 0 <= idx < num_options else -1


class Speedrun:
    def __init__(self, col: anki.collection.Collection) -> None:
        self.col = col.weakref()

    # Gating engine RPCs (Rust-implemented)
    ##########################################################################

    def activate_cards_for_miss(
        self, question_note_id: int, miss_reason: MissReason.V
    ) -> ActivateCardsResponse:
        """Unsuspend a missed question's linked cards iff the reason qualifies
        (KNOWLEDGE_GAP / MISSING_CONTEXT); a no-op otherwise."""
        return self.col._backend.activate_cards_for_miss(
            question_note_id=question_note_id, miss_reason=miss_reason
        )

    def run_coverage_sweep(self, sample_size: int = 0) -> ActivateCardsResponse:
        """Re-activate a spread of cards across all blueprint topics. A
        sample_size of 0 uses the configured default (never "sweep nothing")."""
        return self.col._backend.run_coverage_sweep(sample_size=sample_size)

    def get_memory_score(self) -> MemoryScoreResponse:
        """Per-topic FSRS mastery + overall point estimate, range, coverage, and
        an explicit abstention flag."""
        return self.col._backend.get_memory_score()

    # Miss-reason flow
    ##########################################################################

    def record_miss_reason(
        self, question_note_id: int, miss_reason: MissReason.V
    ) -> ActivateCardsResponse:
        """Persist the latest miss reason as a `miss::<reason>` note tag,
        replacing any prior one (D-11), then run gated activation.

        Attempt correctness/time history already lives natively in `revlog`, so
        only the latest reason needs a home; `card.custom_data` is deliberately
        not used.
        """
        suffix = _MISS_REASON_TAG_SUFFIX.get(miss_reason)
        if suffix is not None:
            note = self.col.get_note(NoteId(question_note_id))
            # Keep only the new miss reason: drop any prior miss::* tag, then add.
            note.tags = [t for t in note.tags if not t.startswith(MISS_TAG_PREFIX)]
            note.tags.append(f"{MISS_TAG_PREFIX}{suffix}")
            self.col.update_note(note)
        return self.activate_cards_for_miss(question_note_id, miss_reason)

    # Data-model provisioning (T1 / D-13)
    ##########################################################################

    def setup_mcat(
        self,
        *,
        enable_value_ordering: bool = True,
    ) -> SetupSummary:
        """Idempotently provision the Speedrun data model for MCAT.

        Creates the ``SpeedrunQuestion`` notetype, the ``Speedrun::Questions``
        and ``Speedrun::Cards`` decks, and the starter blueprint config; turns
        on value ordering; and purges any leftover synthetic demo data from an
        older build. Real practice questions come exclusively from
        :meth:`import_question_bank` — setup never creates placeholder content.

        Re-running is safe: existing objects are reused.
        """
        notetype_id = self.ensure_question_notetype()
        questions_deck, flashcards_deck = self.ensure_decks()
        blueprint = self.ensure_blueprint()

        if self.col.get_config(SWEEP_SAMPLE_SIZE_CONFIG_KEY) is None:
            self.col.set_config(SWEEP_SAMPLE_SIZE_CONFIG_KEY, 2)
        for key, default in (
            (SESSION_PRACTICE_CAP_CONFIG_KEY, DEFAULT_SESSION_PRACTICE_CAP),
            (SESSION_FLASHCARD_CAP_CONFIG_KEY, DEFAULT_SESSION_FLASHCARD_CAP),
            (SESSION_RECAP_CAP_CONFIG_KEY, DEFAULT_SESSION_RECAP_CAP),
        ):
            if self.col.get_config(key) is None:
                self.col.set_config(key, default)
        if enable_value_ordering:
            # Opt into value = topic_weight x weakness ordering of activated cards.
            self.col.set_config(ORDERING_CONFIG_KEY, True)

        demo_removed = self.purge_demo_data()

        return SetupSummary(
            notetype_id=int(notetype_id),
            questions_deck_id=int(questions_deck),
            flashcards_deck_id=int(flashcards_deck),
            blueprint_topics=len(blueprint.get("topics", [])),
            bank_imported=self.has_question_bank(),
            served_question_count=len(self.served_question_note_ids()),
            demo_notes_removed=demo_removed,
        )

    def has_question_bank(self) -> bool:
        """True once the real question bank has been imported (served questions
        exist). The study loop is gated on this so students never practise
        against an empty or synthetic pool."""
        return bool(self.col.find_notes(f"tag:{BANK_TAG} tag:{POOL_SERVED_TAG}"))

    def purge_demo_data(self) -> int:
        """Delete every leftover synthetic demo note (tagged ``LEGACY_DEMO_TAG``)
        and return how many were removed.

        No synthetic content is created anymore; this only cleans up collections
        that were provisioned by an older build so the study loop serves real
        imported questions exclusively. Idempotent and cheap when nothing
        matches.
        """
        demo_notes = list(self.col.find_notes(f"tag:{LEGACY_DEMO_TAG}"))
        if demo_notes:
            self.col.remove_notes(demo_notes)
        return len(demo_notes)

    def import_question_bank(
        self,
        path: str | Path | None = None,
        *,
        questions: list[dict[str, Any]] | None = None,
        attribution: list[dict[str, str]] | None = None,
    ) -> BankImportSummary:
        """Import the vendored real question bank as native ``SpeedrunQuestion``
        notes, so a single desktop import syncs to every device (D-2/D-4).

        Idempotent: each item carries a stable ``bankuid::`` tag, so re-running —
        or running after the bank has already synced from another device — never
        duplicates. Pass ``questions`` to import an in-memory list (used by
        tests); otherwise the JSON at ``path`` (default: the vendored bank) is
        read.
        """
        if questions is None:
            data = load_question_bank(path)
            questions = data.get("questions", [])
            if attribution is None:
                attribution = data.get("attribution", [])

        notetype_id = self.ensure_question_notetype()
        questions_deck, _ = self.ensure_decks()
        notetype = self.col.models.get(notetype_id)
        assert notetype is not None

        existing = self._existing_bank_uids()
        summary = BankImportSummary(
            total_in_bank=len(questions), attribution=attribution or []
        )
        for item in questions:
            uid = str(item.get("uid", "")).strip()
            if not uid or uid in existing:
                summary.skipped_existing += 1
                continue
            note = self._new_bank_note(notetype, item, uid)
            self.col.add_note(note, questions_deck)
            existing.add(uid)
            summary.imported += 1
            origin = str(item.get("origin", "unknown"))
            pool = "heldout" if item.get("pool") == "heldout" else "served"
            summary.by_origin[origin] = summary.by_origin.get(origin, 0) + 1
            summary.by_pool[pool] = summary.by_pool.get(pool, 0) + 1
            for topic in item.get("topics", []):
                summary.by_topic[topic] = summary.by_topic.get(topic, 0) + 1
        return summary

    def import_first_principles(
        self,
        path: str | Path | None = None,
        *,
        cards: list[dict[str, Any]] | None = None,
        suspend: bool = True,
    ) -> FirstPrinciplesImportSummary:
        """Import the vendored first-principles memory cards as native, suspended
        ``Basic`` notes in ``Speedrun::Cards`` (D-2a linked flashcards).

        These are the activation *targets*: linked to questions by a shared
        ``topic::`` tag, they stay suspended until a related question is missed
        for a memory reason. Idempotent via a per-card ``fpuid::`` tag, so
        re-running — or running after they have synced from another device —
        never duplicates. Pass ``cards`` to import an in-memory list (tests);
        otherwise the JSON at ``path`` (default: the vendored set) is read.
        """
        if cards is None:
            cards = load_first_principles(path).get("cards", [])

        _, flashcards_deck = self.ensure_decks()
        basic = self.col.models.by_name(FLASHCARD_NOTETYPE_NAME)
        assert basic is not None, "stock Basic notetype must exist"

        existing = self._existing_first_principles_uids()
        summary = FirstPrinciplesImportSummary(total=len(cards))
        new_card_ids: list[Any] = []
        for item in cards:
            uid = str(item.get("uid", "")).strip()
            if not uid or uid in existing:
                summary.skipped_existing += 1
                continue
            note = self.col.new_note(basic)
            note["Front"] = str(item.get("front", ""))
            note["Back"] = str(item.get("back", ""))
            topic = str(item.get("topic", "")).strip()
            tags = [FIRST_PRINCIPLES_TAG, f"{FIRST_PRINCIPLES_UID_TAG_PREFIX}{uid}"]
            if topic:
                tags.append(f"{TOPIC_TAG_PREFIX}{topic}")
            if concept := str(item.get("concept", "")).strip():
                tags.append(f"{CONCEPT_TAG_PREFIX}{concept}")
            note.tags = tags
            self.col.add_note(note, flashcards_deck)
            existing.add(uid)
            summary.imported += 1
            if topic:
                summary.by_topic[topic] = summary.by_topic.get(topic, 0) + 1
            new_card_ids.extend(c.id for c in note.cards())

        if suspend and new_card_ids:
            # Suspend so they are inert until a missed question activates them.
            self.col.sched.suspend_cards(new_card_ids)
            summary.suspended = len(new_card_ids)
        return summary

    def has_first_principles(self) -> bool:
        """True if any first-principles memory cards have been imported."""
        return bool(self.col.find_notes(f"tag:{FIRST_PRINCIPLES_TAG}"))

    def reset_profile(self) -> ResetProfileSummary:
        """Reset the learner's Speedrun *progress*, keeping all imported content.

        Restores the pristine post-import state so activation and the Memory
        model start fresh, WITHOUT deleting the question bank or the memory
        cards. It:

        * clears any paused guided-session state, so a stale session does not
          resume;
        * forgets every first-principles memory card (``schedule_cards_as_new``),
          which clears their FSRS ``memory_state`` so ``graded_count`` returns to
          0 and they read as ungraded again;
        * re-suspends those cards, returning them to the inert state they start
          in (activation begins from scratch).

        Idempotent and safe on a collection with no Speedrun data.
        """
        summary = ResetProfileSummary()

        # 1. Drop any paused session so Start does not resume old progress.
        if self.col.get_config(SESSION_STATE_CONFIG_KEY, None) is not None:
            self.col.remove_config(SESSION_STATE_CONFIG_KEY)
            summary.session_cleared = True

        # 2. Gather the memory cards and how much progress they carry (measured
        #    before mutating, so the reported counts are meaningful).
        all_ids = list(self.col.find_cards(f"tag:{FIRST_PRINCIPLES_TAG}"))
        if not all_ids:
            return summary
        summary.cards_resuspended = len(
            self.col.find_cards(f"tag:{FIRST_PRINCIPLES_TAG} -is:suspended")
        )
        summary.cards_forgotten = len(
            self.col.find_cards(f"tag:{FIRST_PRINCIPLES_TAG} -is:new")
        )

        # 3. Forget first (clears memory_state and unsuspends into the new
        #    queue), then re-suspend so they end inert with no FSRS history.
        self.col.sched.schedule_cards_as_new(all_ids)
        self.col.sched.suspend_cards(all_ids)
        return summary

    def _existing_first_principles_uids(self) -> set[str]:
        """Stable ids of already-imported first-principles cards (idempotency)."""
        prefix = FIRST_PRINCIPLES_UID_TAG_PREFIX
        return {
            tag[len(prefix) :] for tag in self.col.tags.all() if tag.startswith(prefix)
        }

    def _existing_bank_uids(self) -> set[str]:
        """Stable ids of already-imported bank notes (for idempotent import)."""
        prefix = BANK_UID_TAG_PREFIX
        return {
            tag[len(prefix) :] for tag in self.col.tags.all() if tag.startswith(prefix)
        }

    def _new_bank_note(self, notetype: Any, item: dict[str, Any], uid: str) -> Note:
        """Build (but don't add) a ``SpeedrunQuestion`` note from a bank item."""
        note = self.col.new_note(notetype)
        note["stem"] = str(item.get("stem", ""))
        # Collapse intra-option whitespace so each option stays on one line
        # (the study loop parses ``options`` line-by-line).
        note["options"] = "\n".join(
            " ".join(str(opt).split()) for opt in item.get("options", [])
        )
        note["correct"] = str(item.get("correct", ""))
        note["explanation"] = str(item.get("explanation", ""))
        note["source"] = str(item.get("source", ""))
        note["difficulty_b"] = f"{float(item.get('difficulty_b', 0.0)):.2f}"
        note["discrimination_a"] = f"{float(item.get('discrimination_a', 1.0)):.2f}"

        tags = [f"{TOPIC_TAG_PREFIX}{topic}" for topic in item.get("topics", [])]
        tags.append(
            POOL_HELDOUT_TAG if item.get("pool") == "heldout" else POOL_SERVED_TAG
        )
        tags.append(BANK_TAG)
        tags.append(f"{BANK_UID_TAG_PREFIX}{uid}")
        tags.append(f"{BANK_SOURCE_TAG_PREFIX}{item.get('origin', 'unknown')}")
        if item.get("ai_generated"):
            tags.append(BANK_AI_GENERATED_TAG)
        note.tags = tags
        return note

    def ensure_question_notetype(self) -> NotetypeId:
        """Return the ``SpeedrunQuestion`` notetype id, creating it if absent."""
        models = self.col.models
        existing = models.id_for_name(QUESTION_NOTETYPE_NAME)
        if existing is not None:
            return existing

        notetype = models.new(QUESTION_NOTETYPE_NAME)
        for field_name in QUESTION_FIELDS:
            models.add_field(notetype, models.new_field(field_name))
        template = models.new_template("Card 1")
        template["qfmt"] = "{{stem}}\n<hr id=options>\n{{options}}"
        template["afmt"] = (
            "{{FrontSide}}\n<hr id=answer>\n"
            "<b>Correct:</b> {{correct}}<br>\n{{explanation}}<br>\n"
            "<small>{{source}}</small>"
        )
        models.add_template(notetype, template)
        models.add_dict(notetype)

        created = models.id_for_name(QUESTION_NOTETYPE_NAME)
        assert created is not None
        return created

    def ensure_decks(self) -> tuple[DeckId, DeckId]:
        """Return (questions_deck_id, flashcards_deck_id), creating as needed."""
        questions = self.col.decks.id(QUESTIONS_DECK_NAME)
        flashcards = self.col.decks.id(FLASHCARDS_DECK_NAME)
        assert questions is not None and flashcards is not None
        return questions, flashcards

    def ensure_blueprint(
        self,
        blueprint: dict[str, Any] | None = None,
        *,
        overwrite: bool = False,
    ) -> dict[str, Any]:
        """Persist the MCAT blueprint config (D-3). Existing config is kept
        unless ``overwrite`` is set; pass ``blueprint`` to override the default
        (D-3 allows a provided file)."""
        existing = self.col.get_config(BLUEPRINT_CONFIG_KEY)
        if existing and not overwrite:
            return existing
        chosen = blueprint if blueprint is not None else DEFAULT_MCAT_BLUEPRINT
        self.col.set_config(BLUEPRINT_CONFIG_KEY, chosen)
        return chosen

    # Question-first study loop support (M2 2b surface, minimal M1 slice)
    ##########################################################################

    def served_question_note_ids(self) -> list[NoteId]:
        """Note ids of served (never held-out) practice questions, in a stable
        interleaved-ish order. Held-out questions are never returned."""
        query = (
            f"note:{QUESTION_NOTETYPE_NAME} tag:{POOL_SERVED_TAG} "
            f"-tag:{POOL_HELDOUT_TAG}"
        )
        return list(self.col.find_notes(query, order=True))

    def served_questions_interleaved(
        self,
        *,
        topics: set[str] | None = None,
        exclude: set[int] | None = None,
        unseen_first: bool = False,
    ) -> list[NoteId]:
        """Served question note ids interleaved across topics (no topic blocking).

        ``topics`` restricts the result to those bare topic names (used by the
        recap phase to target only the just-studied topics); ``exclude`` drops
        specific note ids (used to keep the recap set disjoint from Phase 1).

        ``unseen_first`` orders never-practised questions (their card has zero
        reps) ahead of already-practised ones so a capped batch (e.g. a guided
        session's Practice phase) never re-serves the same problems while fresh
        ones remain. Once the whole served pool has been practised, previously
        seen questions come back rotated oldest-review-first, so repeats are the
        least recently seen rather than always the same leading batch.

        Note: this loads each served note to read its ``topic::`` tag (and, when
        ``unseen_first`` is set, its card's review state). The served pool is
        small (tens of items) so this is cheap; revisit if it grows.
        """
        exclude = exclude or set()

        def in_scope(nid: NoteId) -> str | None:
            """Return the bare topic if ``nid`` is in scope, else ``None``."""
            if nid in exclude:
                return None
            topic = topic_of_note(self.col.get_note(nid)) or ""
            if topics is not None and topic not in topics:
                return None
            return topic

        if not unseen_first:
            groups: dict[str, list[NoteId]] = {}
            for nid in self.served_question_note_ids():
                topic = in_scope(nid)
                if topic is None:
                    continue
                groups.setdefault(topic, []).append(nid)
            return _round_robin(list(groups.values()))

        # Partition into never-practised vs. practised. Practised questions are
        # sorted oldest-review-first so, once the pool is exhausted, repeats
        # rotate rather than always replaying the same leading batch.
        unseen_groups: dict[str, list[NoteId]] = {}
        seen: list[tuple[int, str, NoteId]] = []
        for nid in self.served_question_note_ids():
            topic = in_scope(nid)
            if topic is None:
                continue
            cards = self.col.get_note(nid).cards()
            card = cards[0] if cards else None
            if card is None or card.reps == 0:
                unseen_groups.setdefault(topic, []).append(nid)
            else:
                seen.append((card.last_review_time or 0, topic, nid))

        result = _round_robin(list(unseen_groups.values()))
        seen.sort(key=lambda item: item[0])
        seen_groups: dict[str, list[NoteId]] = {}
        for _last_review, topic, nid in seen:
            seen_groups.setdefault(topic, []).append(nid)
        result.extend(_round_robin(list(seen_groups.values())))
        return result

    def session_caps(self) -> SessionCaps:
        """Per-phase caps for a guided session, from config (with defaults)."""

        def cap(key: str, default: int) -> int:
            value = self.col.get_config(key)
            try:
                value = int(value)
            except (TypeError, ValueError):
                return default
            return value if value > 0 else default

        return SessionCaps(
            practice=cap(SESSION_PRACTICE_CAP_CONFIG_KEY, DEFAULT_SESSION_PRACTICE_CAP),
            flashcards=cap(
                SESSION_FLASHCARD_CAP_CONFIG_KEY, DEFAULT_SESSION_FLASHCARD_CAP
            ),
            recap=cap(SESSION_RECAP_CAP_CONFIG_KEY, DEFAULT_SESSION_RECAP_CAP),
        )
